name: Deploy to GitHub Pages

on:
  push:
    branches: ['lesson_9']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install
        run: cd ./my-app && npm install
      - name: Build
        run: cd ./my-app && npm run build
      - name: Deploy
        run: cd ./my-app && npm run deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
